name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bullseye

    steps:
      - run: apt update && apt install curl
      - run: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag mizore/nginx
      - name: Push to Docker Hub
        run: docker push mizore/nginx
