name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Login Docker hub
      run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag mizore/nginx
    - name: Push Docker image
      run: docker push mizore/nginx
